### PR TITLE
update dependencies.md

### PR DESCRIPTION
**Pull request by scottf**

### CODE REVIEW

**Review by YunaBraska — APPROVED** [review]

**Comment by YunaBraska** [comment]
Just curious, Is this auto generated or manually written?

**Comment by scottf** [comment]
Thanks @YunaBraska

**Comment by scottf** [comment]
Manually starting with output from `mvn dependency:tree`. Is there a better way?

**Comment by YunaBraska** [comment]
I don't know an automatic way, but it seems interesting to automate this :D

**Pull request merged**
